"""initial schema

Revision ID: 0d06edab116e
Revises:
Create Date: 2026-08-28 22:20:55.793803

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0d06edab116e"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "authors",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("normalized_name", sa.String(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_authors_normalized_name"), "authors", ["normalized_name"], unique=True
    )
    op.create_table(
        "genres",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "manga",
        sa.Column("mal_id", sa.Integer(), nullable=True),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("published_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "ongoing",
                "finished",
                "cancelled",
                "not_released_yet",
                "hiatus",
                name="manga_status",
            ),
            nullable=True,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("mal_id"),
    )
    op.create_table(
        "sources",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("weight", sa.Float(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "users",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("role", sa.Enum("admin", "user", name="user_role"), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_table(
        "manga_authors",
        sa.Column("manga_id", sa.UUID(), nullable=False),
        sa.Column("author_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["author_id"], ["authors.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["manga_id"], ["manga.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("manga_id", "author_id"),
    )
    op.create_index(op.f("ix_manga_authors_author_id"), "manga_authors", ["author_id"])
    op.create_table(
        "manga_external_ratings",
        sa.Column("manga_id", sa.UUID(), nullable=False),
        sa.Column("source_id", sa.UUID(), nullable=False),
        sa.Column("external_id", sa.String(), nullable=False),
        sa.Column("raw_scale_max", sa.Float(), nullable=True),
        sa.Column("votes_count", sa.Integer(), nullable=True),
        sa.Column("fetched_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("raw_score", sa.Float(), nullable=True),
        sa.Column("score_distribution", sa.ARRAY(sa.Integer()), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["manga_id"], ["manga.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["sources.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("source_id", "external_id"),
    )
    op.create_index(
        op.f("ix_manga_external_ratings_manga_id"),
        "manga_external_ratings",
        ["manga_id"],
    )
    op.create_table(
        "manga_genres",
        sa.Column("manga_id", sa.UUID(), nullable=False),
        sa.Column("genre_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["genre_id"], ["genres.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["manga_id"], ["manga.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("manga_id", "genre_id"),
    )
    op.create_index(op.f("ix_manga_genres_genre_id"), "manga_genres", ["genre_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_manga_genres_genre_id"), table_name="manga_genres")
    op.drop_table("manga_genres")
    op.drop_index(
        op.f("ix_manga_external_ratings_manga_id"), table_name="manga_external_ratings"
    )
    op.drop_table("manga_external_ratings")
    op.drop_index(op.f("ix_manga_authors_author_id"), table_name="manga_authors")
    op.drop_table("manga_authors")
    op.drop_table("users")
    op.drop_table("sources")
    op.drop_table("manga")
    op.drop_table("genres")
    op.drop_index(op.f("ix_authors_normalized_name"), table_name="authors")
    op.drop_table("authors")
    # ### end Alembic commands ###
    # Dropping a table leaves its enum type behind, so a later upgrade fails
    # with "type already exists". Alembic does not generate these.
    sa.Enum(name="manga_status").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="user_role").drop(op.get_bind(), checkfirst=True)
