"""add manga type, english title, tag explicit flag

Revision ID: 3ebb7d2a1701
Revises: fec907e3a4f4
Create Date: 2026-09-12 21:18:25.503843

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3ebb7d2a1701"
down_revision: str | Sequence[str] | None = "fec907e3a4f4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# ADD COLUMN does not create the enum, so this migration creates it by hand.
manga_type = postgresql.ENUM(
    "manga",
    "light_novel",
    "manhwa",
    "one_shot",
    "doujinshi",
    "manhua",
    name="manga_type",
    create_type=False,
)


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    manga_type.create(op.get_bind(), checkfirst=True)
    op.add_column("manga", sa.Column("type", manga_type, nullable=True))
    op.add_column("manga", sa.Column("title_english", sa.String(), nullable=True))
    op.alter_column(
        "manga",
        "published_date",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        type_=sa.Date(),
        existing_nullable=True,
        postgresql_using="published_date AT TIME ZONE 'UTC'",
    )
    op.add_column(
        "tags",
        sa.Column(
            "is_explicit", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tags", "is_explicit")
    op.alter_column(
        "manga",
        "published_date",
        existing_type=sa.Date(),
        type_=postgresql.TIMESTAMP(timezone=True),
        existing_nullable=True,
        postgresql_using="published_date::timestamp AT TIME ZONE 'UTC'",
    )
    op.drop_column("manga", "title_english")
    op.drop_column("manga", "type")
    manga_type.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
