"""add description to manga

Revision ID: 423ec680e0d3
Revises: 9fd643e69e88
Create Date: 2026-08-10 14:27:57.775680

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "423ec680e0d3"
down_revision: str | Sequence[str] | None = "9fd643e69e88"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("manga", sa.Column("description", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("manga", "description")
    # ### end Alembic commands ###
