"""add manga is_explicit

Revision ID: 508adf962ff9
Revises: 3ebb7d2a1701
Create Date: 2026-09-26 21:39:44.918527

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "508adf962ff9"
down_revision: str | Sequence[str] | None = "3ebb7d2a1701"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "manga",
        sa.Column(
            "is_explicit", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
    )
    op.execute(
        """
        UPDATE manga SET is_explicit = true
        WHERE EXISTS (
            SELECT 1
            FROM manga_tags
            JOIN tags ON tags.id = manga_tags.tag_id
            WHERE manga_tags.manga_id = manga.id
              AND tags.normalized_name IN ('hentai', 'erotica')
        )
        """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("manga", "is_explicit")
    # ### end Alembic commands ###
