"""drop manga_id and source_id unique on manga_external_ratings

Revision ID: 591b389bfedd
Revises: 81a4d72f8c56
Create Date: 2026-08-28 18:28:05.800944

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "591b389bfedd"
down_revision: str | Sequence[str] | None = "81a4d72f8c56"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("manga_external_ratings_manga_id_source_id_key"),
        "manga_external_ratings",
        type_="unique",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        op.f("manga_external_ratings_manga_id_source_id_key"),
        "manga_external_ratings",
        ["manga_id", "source_id"],
        postgresql_nulls_not_distinct=False,
    )
    # ### end Alembic commands ###
