"""initial schema

Revision ID: 6a32263ab208
Revises:
Create Date: 2026-08-29 23:39:37.293505

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6a32263ab208"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "authors",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("normalized_name", sa.String(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_authors_normalized_name"), "authors", ["normalized_name"], unique=True
    )
    op.create_table(
        "manga",
        sa.Column("mal_id", sa.Integer(), nullable=True),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("published_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "ongoing",
                "finished",
                "cancelled",
                "not_released_yet",
                "hiatus",
                name="manga_status",
            ),
            nullable=True,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("mal_id"),
    )
    op.create_table(
        "sources",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("weight", sa.Float(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "tags",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("normalized_name", sa.String(), nullable=False),
        sa.Column("category", sa.String(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_tags_normalized_name"), "tags", ["normalized_name"], unique=True
    )
    op.create_table(
        "users",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("role", sa.Enum("admin", "user", name="user_role"), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_table(
        "manga_authors",
        sa.Column("manga_id", sa.UUID(), nullable=False),
        sa.Column("author_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["author_id"], ["authors.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["manga_id"], ["manga.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("manga_id", "author_id"),
    )
    op.create_index(
        op.f("ix_manga_authors_author_id"), "manga_authors", ["author_id"], unique=False
    )
    op.create_table(
        "manga_external_ratings",
        sa.Column("manga_id", sa.UUID(), nullable=False),
        sa.Column("source_id", sa.UUID(), nullable=False),
        sa.Column("external_id", sa.String(), nullable=False),
        sa.Column("raw_scale_max", sa.Float(), nullable=True),
        sa.Column("votes_count", sa.Integer(), nullable=True),
        sa.Column("fetched_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("raw_score", sa.Float(), nullable=True),
        sa.Column("score_distribution", sa.ARRAY(sa.Integer()), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["manga_id"], ["manga.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["sources.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("source_id", "external_id"),
    )
    op.create_index(
        op.f("ix_manga_external_ratings_manga_id"),
        "manga_external_ratings",
        ["manga_id"],
        unique=False,
    )
    op.create_table(
        "manga_tags",
        sa.Column("manga_id", sa.UUID(), nullable=False),
        sa.Column("tag_id", sa.UUID(), nullable=False),
        sa.Column("rank", sa.Integer(), nullable=True),
        sa.Column(
            "is_spoiler", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.ForeignKeyConstraint(["manga_id"], ["manga.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tag_id"], ["tags.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("manga_id", "tag_id"),
    )
    op.create_index(
        op.f("ix_manga_tags_tag_id"), "manga_tags", ["tag_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_manga_tags_tag_id"), table_name="manga_tags")
    op.drop_table("manga_tags")
    op.drop_index(
        op.f("ix_manga_external_ratings_manga_id"), table_name="manga_external_ratings"
    )
    op.drop_table("manga_external_ratings")
    op.drop_index(op.f("ix_manga_authors_author_id"), table_name="manga_authors")
    op.drop_table("manga_authors")
    op.drop_table("users")
    op.drop_index(op.f("ix_tags_normalized_name"), table_name="tags")
    op.drop_table("tags")
    op.drop_table("sources")
    op.drop_table("manga")
    op.drop_index(op.f("ix_authors_normalized_name"), table_name="authors")
    op.drop_table("authors")
    # ### end Alembic commands ###
