"""add score distribution col to manga external ratings

Revision ID: 81a4d72f8c56
Revises: 423ec680e0d3
Create Date: 2026-08-22 14:44:12.862059

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "81a4d72f8c56"
down_revision: str | Sequence[str] | None = "423ec680e0d3"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "manga_external_ratings",
        sa.Column("score_distribution", sa.ARRAY(sa.Integer()), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("manga_external_ratings", "score_distribution")
    # ### end Alembic commands ###
