"""add manga_metrics

Revision ID: b10ed86b8d1b
Revises: 258f0f1bf92c
Create Date: 2026-09-05 21:00:16.827684

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "b10ed86b8d1b"
down_revision: str | Sequence[str] | None = "258f0f1bf92c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
