"""add mal_id, sources, manga_external_ratings

Revision ID: c2ee0044922b
Revises: c7c932d09115
Create Date: 2026-08-05 21:55:20.433291

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c2ee0044922b"
down_revision: str | Sequence[str] | None = "c7c932d09115"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sources",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("weight", sa.Float(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "manga_external_ratings",
        sa.Column("manga_id", sa.UUID(), nullable=False),
        sa.Column("source_id", sa.UUID(), nullable=False),
        sa.Column("external_id", sa.String(), nullable=False),
        sa.Column("raw_scale_max", sa.Float(), nullable=True),
        sa.Column("votes_count", sa.Integer(), nullable=True),
        sa.Column("fetched_at", sa.DateTime(), nullable=False),
        sa.Column("raw_score", sa.Float(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["manga_id"],
            ["manga.id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["sources.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("manga_id", "source_id"),
        sa.UniqueConstraint("source_id", "external_id"),
    )
    op.add_column("manga", sa.Column("mal_id", sa.Integer(), nullable=True))
    op.create_unique_constraint(None, "manga", ["mal_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "manga", type_="unique")
    op.drop_column("manga", "mal_id")
    op.drop_table("manga_external_ratings")
    op.drop_table("sources")
    # ### end Alembic commands ###
