"""add manga_similarity

Revision ID: e3004a81027d
Revises: 508adf962ff9
Create Date: 2026-09-27 21:02:17.505431

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e3004a81027d"
down_revision: str | Sequence[str] | None = "508adf962ff9"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "manga_similarities",
        sa.Column("manga_id", sa.UUID(), nullable=False),
        sa.Column(
            "method",
            sa.Enum("community_recs", "collab", name="similarity_method"),
            nullable=False,
        ),
        sa.Column("similar_manga_id", sa.UUID(), nullable=False),
        sa.Column("score", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(["manga_id"], ["manga.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["similar_manga_id"], ["manga.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("manga_id", "method", "similar_manga_id"),
    )
    op.create_index(
        op.f("ix_manga_similarities_similar_manga_id"),
        "manga_similarities",
        ["similar_manga_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_manga_similarities_similar_manga_id"), table_name="manga_similarities"
    )
    op.drop_table("manga_similarities")
    # ### end Alembic commands ###
    # drop_table leaves the enum type behind, and the next upgrade fails on it.
    sa.Enum(name="similarity_method").drop(op.get_bind(), checkfirst=True)
