"""fix manga_metrics

Revision ID: f986558dad8c
Revises: b10ed86b8d1b
Create Date: 2026-09-05 21:03:04.560901

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f986558dad8c"
down_revision: str | Sequence[str] | None = "b10ed86b8d1b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "manga_metrics",
        sa.Column("manga_id", sa.UUID(), nullable=False),
        sa.Column("bayesian_score", sa.Float(), nullable=False),
        sa.Column("mean_score", sa.Float(), nullable=False),
        sa.Column("votes_count", sa.Integer(), nullable=False),
        sa.Column("source_count", sa.Integer(), nullable=False),
        sa.Column("computed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["manga_id"], ["manga.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("manga_id"),
    )
    op.create_index(
        op.f("ix_manga_metrics_bayesian_score"),
        "manga_metrics",
        ["bayesian_score"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_manga_metrics_bayesian_score"), table_name="manga_metrics")
    op.drop_table("manga_metrics")
    # ### end Alembic commands ###
