"""add manga_embeddings

Revision ID: fec907e3a4f4
Revises: 21d7e2adcc88
Create Date: 2026-09-11 13:50:51.652594

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy

# revision identifiers, used by Alembic.
revision: str = "fec907e3a4f4"
down_revision: Union[str, Sequence[str], None] = "21d7e2adcc88"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.create_table(
        "manga_embeddings",
        sa.Column("manga_id", sa.UUID(), nullable=False),
        sa.Column(
            "content_vector",
            pgvector.sqlalchemy.halfvec.HALFVEC(dim=384),
            nullable=False,
        ),
        sa.Column("model_name", sa.String(), nullable=False),
        sa.Column("computed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("cluster_id", sa.Integer(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["manga_id"], ["manga.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("manga_id"),
    )
    op.create_index(
        "ix_manga_embeddings_content_vector",
        "manga_embeddings",
        ["content_vector"],
        unique=False,
        postgresql_using="hnsw",
        postgresql_ops={"content_vector": "halfvec_ip_ops"},
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_manga_embeddings_content_vector",
        table_name="manga_embeddings",
        postgresql_using="hnsw",
        postgresql_ops={"content_vector": "halfvec_ip_ops"},
    )
    op.drop_table("manga_embeddings")
    # ### end Alembic commands ###
